print("hello")
name=input("enter the student name:")
roll_number=input("enter your roll number:")
print("Name of student:",name)
print("Student roll number:",roll_number)
cgpa=float(input("enter student cgpa:"))
percentage=("enter percentage of student:")
Percentage_of_student=cgpa*10
print("Cgpa of student:",cgpa)
print("percentage of student:",percentage)